# Properties defining configuration for the Deep Thought, Spring Boot application.

spring.application.name=Image Generation

# OpenAI
spring.ai.openai.api-key=
spring.ai.openai.image.options.model=dall-e-2
