# Properties defining configuration for the Deep Thought, Spring Boot application.

spring.application.name=Embeddings App

spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.openai.embedding.options.model=text-embedding-3-small
