services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: shazam-database
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: shazam
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: shazam_db
    ports:
      - "5432:5432"
    volumes:
      - shazam_db_data:/var/lib/postgresql/data

volumes:
  shazam_db_data:
