services:
  postgres:
    image: postgres:18-alpine
    container_name: shazam-database
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: shazam_db
      POSTGRES_USER: shazam
      POSTGRES_PASSWORD: s3cr3t
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - shazam_db_data:/var/lib/postgresql/data

volumes:
  shazam_db_data:
