# Property configuration for the Pre-Generated Answers Spring Boot application.

spring.application.name=Pre-Generated Answer App

example.app.pre-generated-answers.embeddings.similarity-threshold=0.90
example.app.pre-generated-answers.embeddings.top-k=20

# Ollama
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text
