# User-specific properties for OpenAI and Google Gemini.

spring.ai.openai.api-key=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
spring.ai.vertex.ai.gemini.projectId=chef-ai-429907
