# Properties defining configuration for the Stock Quotes Spring Boot application.

spring.application.name=Stock Quotes App

# Google Gemini
spring.ai.vertex.ai.gemini.projectId=
spring.ai.vertex.ai.gemini.location=us-west1
