# Spring Boot application.properties defining configuration for the Stock Quote application.

spring.application.name=Stock Quote

# Google Gemini
spring.ai.vertex.ai.gemini.projectId=
spring.ai.vertex.ai.gemini.location=us-west1
