# Property configuration for the Image Generation Spring Boot application.

spring.application.name=Image Generation App

# OpenAI
spring.ai.openai.api-key=
spring.ai.openai.image.options.model=dall-e-2
