# Properties defining configuration for the Current Time Spring Boot application.

spring.application.name=Current Time

# Google Gemini
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o
