# Property configuration for the Current Time Spring Boot application.

spring.application.name=Current Time App

# OpenAI
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o-mini

# Google Vertex AI Gemini
spring.ai.vertex.ai.gemini.projectId=
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash-lite
spring.ai.vertex.ai.gemini.location=us-west1
