# Properties defining configuration for the Song Similarity Search example, Spring Boot application.

logging.level.root=WARN

spring.application.name=Song Similarity Search App

spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.openai.embedding.options.model=text-embedding-3-small
