# Property configuration for the Song Similarity Search Spring Boot application.

logging.level.root=WARN

spring.application.name=Song Similarity Search App

spring.ai.ollama.embedding.options.model=nomic-embed-text
