# Property configuration for the Song Similarity Search Spring Boot application.

logging.level.root=WARN

spring.application.name=Song Similarity Search App

# Mistral AI
#spring.ai.mistralai.embedding.options.model=

# Ollama
spring.ai.ollama.embedding.options.model=nomic-embed-text
