# Property configuration for the Connect 4 Spring Boot, Spring AI application

spring.application.name=connect4 app

spring.ai.retry.max-attempts=1

logging.level.com.packt.spring.ai.examples.connect4.ConnectFourApplication=INFO
