# User-specific properties for OpenAI and Google Gemini.

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.vertex.ai.gemini.projectId=springai-459600
spring.ai.vertex.ai.gemini.location=us-west1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash-001
