# Property configuration for Image Vision Spring Boot application.

spring.application.name=Image Vision App

# Logging
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# Mistral
spring.ai.mistralai.api-key=
spring.ai.mistralai.chat.options.model=pixtral-12b-2409

# Ollama
spring.ai.ollama.chat.options.model=llama3.2-vision

# OpenAI
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o-mini
