# Properties defining configuration for the Stock Quotes Tool Calling (Function) Example Spring Boot application

spring.application.name=Stock Quotes App

# Ollama
spring.ai.ollama.chat.options.model=functiongemma

# Polygon
examples.app.stock-quotes.polygon.api.key=
examples.app.stock-quotes.polygon.api.base-url=https://api.polygon.io/v2
examples.app.stock-quotes.polygon.api.market-data.previous-close.uri=/aggs/ticker/{exchangeSymbol}/prev?adjusted=true
