[[embeddings-example]]
= Embeddings Example

This Spring AI example contains a simple Spring Boot application using Spring AI's https://docs.spring.io/spring-ai/reference/api/embeddings.html[Embeddings Model API] to embed an object, such as text, into a Vector. Vectors are used to find similarity and ultimately meaning in content.

By default, this example runs Spring AI with https://ollama.com[Ollama] using the `nomic-embed-text` model. See Spring AI documentation on https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html[using Ollama].

> NOTE: Using Ollama allows you to run AI models locally. Goto https://ollama.com/download[download] and install Ollama on your computer. To install a AI model locally, such as `nomic-embed-text`, run `$ ollama run nomic-embed-text`.

To run the program, enter the following Maven command at the command-line:

```bash
$ mvnw --projects embeddings-example spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.packt.spring.ai:embeddings-example >---------------
[INFO] Building EmbeddingsExample 0.3.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot:3.5.3:run (default-cli) > test-compile @ embeddings-example >>>
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ embeddings-example ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO]
[INFO] --- compiler:3.14.0:compile (default-compile) @ embeddings-example ---
[INFO] Nothing to compile - all classes are up to date.
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ embeddings-example ---
[INFO] skip non existing resourceDirectory /Users/jxblum/cpdev/Packt/Building Intelligent Applications with Spring AI/spring-ai-examples/embeddings-example/src/test/resources
[INFO]
[INFO] --- compiler:3.14.0:testCompile (default-testCompile) @ embeddings-example ---
[INFO] No sources to compile
[INFO]
[INFO] <<< spring-boot:3.5.3:run (default-cli) < test-compile @ embeddings-example <<<
[INFO]
[INFO]
[INFO] --- spring-boot:3.5.3:run (default-cli) @ embeddings-example ---
[INFO] Attaching agents: []

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.5.3)

2025-07-01T17:20:41.559-07:00  INFO 39305 --- [Embeddings App] [           main] c.p.s.a.e.e.EmbeddingsApplication        : Starting EmbeddingsApplication using Java 17.0.14 with PID 39305 (/Users/jxblum/cpdev/Packt/Building Intelligent Applications with Spring AI/spring-ai-examples/embeddings-example/target/classes started by jxblum in /Users/jxblum/cpdev/Packt/Building Intelligent Applications with Spring AI/spring-ai-examples/embeddings-example)
2025-07-01T17:20:41.561-07:00  INFO 39305 --- [Embeddings App] [           main] c.p.s.a.e.e.EmbeddingsApplication        : The following 1 profile is active: "user"
2025-07-01T17:20:41.975-07:00  INFO 39305 --- [Embeddings App] [           main] c.p.s.a.e.e.EmbeddingsApplication        : Started EmbeddingsApplication in 0.556 seconds (process running for 0.674)
prompt> To be, or not to be, that is the question.
Vector Dimension: 768

```

As you can see from the program output above, the example Spring AI application outputs the Vector size (floating point number array size) of the text, "_To be, or not to be, that is the question._" The result is a Vector size of 768 floating point numbers.
