# Spring Boot application.properties defining configuration for the Deep Thought application.

spring.application.name=Deep Thought

# OpenAI
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o

# Google Gemini
spring.ai.vertex.ai.gemini.projectId=
spring.ai.vertex.ai.gemini.location=us-west1

# Ollama
spring.ai.ollama.chat.options.model=llama3.2
