# Spring Boot application.properties defining configuration for the Current Time application.

spring.application.name=Moderation App

# Google Gemini
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt4o
spring.ai.openai.moderation.options.model=text-moderation-latest
