# Property configuration for the Moderation Spring Boot application.

spring.application.name=Moderation App

# OpenAI
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.moderation.options.model=text-moderation-latest
