spring.ssl.bundle.pem.chat-bundle.keystore.certificate=classpath:chat-certificate.pem
spring.ssl.bundle.pem.chat-bundle.keystore.private-key=classpath:chat-private-key.pem

server.port=8443
server.ssl.bundle=chat-bundle
