[[streaming-example]]
= Streaming Example

This Spring AI example contains a simple Spring Boot application using Spring AI's https://docs.spring.io/spring-ai/reference/api/chatclient.html[Chat Client API] and the Stream API to asynchronously interact with the AI model in a non-blocking, Reactive manner.

By default, this example runs Spring AI with https://ollama.com[Ollama] using Meta's `llama3.2` model. See Spring AI documentation on https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html[using Ollama].

> NOTE: Using Ollama allows you to run AI models locally. Goto https://ollama.com/download[download] and install Ollama on your computer. To install a AI model locally, such as Meta's llama3.2, run `$ ollama run llama3.2`.

The program prompts allows the user to prompt the AI model and ask it any question s/he likes.

To run the program, enter the following Maven command at the command-line:

```bash
$ mvnw --projects streaming-example spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.packt.spring.ai:streaming-example >----------------
[INFO] Building StreamingExample 0.1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot:3.5.3:run (default-cli) > test-compile @ streaming-example >>>
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ streaming-example ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO]
[INFO] --- compiler:3.14.0:compile (default-compile) @ streaming-example ---
[INFO] Nothing to compile - all classes are up to date.
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ streaming-example ---
[INFO] skip non existing resourceDirectory /Users/jxblum/cpdev/Packt/Building Intelligent Applications with Spring AI/spring-ai-examples/streaming-example/src/test/resources
[INFO]
[INFO] --- compiler:3.14.0:testCompile (default-testCompile) @ streaming-example ---
[INFO] No sources to compile
[INFO]
[INFO] <<< spring-boot:3.5.3:run (default-cli) < test-compile @ streaming-example <<<
[INFO]
[INFO]
[INFO] --- spring-boot:3.5.3:run (default-cli) @ streaming-example ---
[INFO] Attaching agents: []

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.5.3)

2025-07-03T16:12:28.672-07:00  INFO 67249 --- [Streaming App] [           main] c.p.s.a.e.s.StreamingApplication         : Starting StreamingApplication using Java 17.0.14 with PID 67249 (/Users/jxblum/cpdev/Packt/Building Intelligent Applications with Spring AI/spring-ai-examples/streaming-example/target/classes started by jxblum in /Users/jxblum/cpdev/Packt/Building Intelligent Applications with Spring AI/spring-ai-examples/streaming-example)
2025-07-03T16:12:28.675-07:00  INFO 67249 --- [Streaming App] [           main] c.p.s.a.e.s.StreamingApplication         : The following 1 profile is active: "user"
2025-07-03T16:12:29.094-07:00  INFO 67249 --- [Streaming App] [           main] c.p.s.a.e.s.StreamingApplication         : Started StreamingApplication in 0.558 seconds (process running for 0.673)

user> How many planets are in our solar system?

ai> There are eight planets in our solar system:

1. Mercury
2. Venus
3. Earth
4. Mars
5. Jupiter
6. Saturn
7. Uranus
8. Neptune

Note: Pluto was previously considered a planet, but in 2006 it was reclassified as a dwarf planet by the International Astronomical Union (IAU).

user>
```

While you cannot observe the programs behavior as described in this README, the AI generated response is output as the model is generating the response. And so, you see the text appears as if someone is typing.

Type "exit" to quit the program.
