# Configuration properties for the Spring Boot, Spring AI Travel Agent application & MCP server

spring.application.name=Travel Agent App

spring.main.web-application-type=none
spring.main.banner-mode=off

spring.ai.mcp.server.name=travel-agent-server
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.version=0.1.0
