# Property configuration for the Connect 4 Spring Boot, Spring AI application

spring.application.name=Connect4 App

spring.ai.retry.max-attempts=1

logging.level.com.packt.spring.ai.examples.connect4.ConnectFourApplication=INFO

# OpenAI
spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.chat.options.temperature=1.0

# Google Vertex AI Gemini
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash-lite
spring.ai.vertex.ai.gemini.location=us-west1
