# Property configuration for the Connect 4 Spring Boot, Spring AI application

spring.application.name=Connect4 App

spring.ai.retry.max-attempts=1

ext.spring.ai.chat.model.logging.level=DEBUG

logging.level.com.packt.spring.ai.examples.connect4.ConnectFourApplication=INFO

# Mistral AI
spring.ai.mistralai.chat.options.model=magistral-small-latest
spring.ai.mistralai.chat.options.responseFormat=json_object

# Ollama (using Meta's llama3.2 AI model)
spring.ai.ollama.chat.options.format=json
spring.ai.ollama.chat.options.model=llama3.2
#spring.ai.ollama.chat.options.model=gpt-oss:20b
#spring.ai.ollama.chat.options.model=deepseek-r1:8b

# OpenAI
spring.ai.openai.chat.options.model=gpt-5-mini
#spring.ai.openai.chat.options.model=o4-mini
spring.ai.openai.chat.options.temperature=1.0

# Google Vertex AI Gemini
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash-lite
spring.ai.vertex.ai.gemini.location=us-west1
