# Configuration properties for the Shazam Spring Boot application

spring.application.name=Shazam app

#shazam.audio.buffer.size=32768
shazam.audio.clip.duration=100ms
#shazam.audio.mp3.bit-rate=192000
#shazam.audio.mp3.sample-rate=22050
#shazam.audio.mp3.sample-size=8
shazam.song.loader.audio-clip.save=false
shazam.song.loader.song.load=true
shazam.song.search.similarity-threshold=0.85
shazam.song.search.topK=5

# Spring AI Configuration
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Shazam Web application configuration
server.servlet.contextPath=/music
spring.servlet.multipart.max-file-size=10MB

# Shazam Docker Services configuration
spring.docker.compose.file=./docker/compose.yml

# Shazam Database configuration
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shazam_db
spring.datasource.username=shazam
spring.datasource.password=s3cr3t
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/database/schema.sql
spring.jpa.open-in-view=false
spring.ai.vectorstore.pgvector.initialize-schema=true

# Shazam Application Environment & Functional configuration
spring.profiles.group.shazam-app[0]=AudioTime
spring.profiles.group.shazam-app[1]=MP3

# Shazam Song Loader Environment & Functional configuration
spring.profiles.group.shazam-song-loader[0]=AudioTime
spring.profiles.group.shazam-song-loader[1]=honerlaw
spring.profiles.group.shazam-song-loader[2]=WAV
