# Configuration properties for the Shazam Spring Boot application

spring.application.name=Shazam app

#shazam.audio.buffer.divisor=15
#shazam.audio.buffer.size=200000
shazam.audio.clip.length=10s
#shazam.audio.mp3.bit-rate=128000
#shazam.audio.mp3.sample-rate=22050
shazam.song.search.similarity-threshold=0.85
#shazam.song.search.topK=8

server.servlet.contextPath=/music

spring.profiles.group.shazam-app[0]=AudioTime
spring.profiles.group.shazam-app[1]=MP3
