# Spring Boot application.properties defining configuration for the Opposites application.

spring.application.name=Opposites

# Google Gemini
spring.ai.vertex.ai.gemini.projectId=
spring.ai.vertex.ai.gemini.location=us-west1
