# Configuration properties for the Spring Boot, Spring AI Travel Agent application using SerpApi

travel-agent.app.provider.serpapi.api-key=
travel-agent.app.provider.serpapi.engine=google
travel-agent.app.provider.serpapi.baseUrl=https://serpapi.com/search?engine=${travel-agent.app.provider.serpapi.engine}
