# Configuration properties for the Spring Boot, Spring AI Travel Agent application using SerpApi

travel-agent.app.provider.serpapi.api-key=
travel-agent.app.provider.serpapi.output=JSON
travel-agent.app.provider.serpapi.engine.flights=google_flights
travel-agent.app.provider.serpapi.engine.hotels=google_hotels
travel-agent.app.provider.serpapi.baseUrl=https://serpapi.com/search
