# Property configuration for Observability Spring Boot application.

spring.application.name=Observability App

spring.ai.ollama.chat.model.options=llama3.2

management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=health,metrics
