[[example-one]]
= Example One

This is the first example from the book, "Building Intelligent Applications with Spring AI".

This example uses Spring AI with OpenAI to demonstrate how to use Spring AI's `ChatModel` API to prompt ChatGPT with a question and receive a generated answer, outputting the response to standard out.

[[example-one-requirements]]
REQUIREMENTS:

1. JDK 17

[[example-one-run]]
RUN:

This example can be run from the project base directory with `mvnw` command:

[source,shell]
----
$ mvnw --projects example-one spring-boot:run
----

The program will output content similar to the following:

[source,text]
----
$ mvnw -projects example-one spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.packt.spring.ai:example-one >-------------------
[INFO] Building ExampleOne 0.1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot:3.5.0:run (default-cli) > test-compile @ example-one >>>
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ example-one ---
[INFO] Copying 2 resources from src/main/resources to target/classes
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO]
[INFO] --- compiler:3.14.0:compile (default-compile) @ example-one ---
[INFO] Nothing to compile - all classes are up to date.
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ example-one ---
[INFO] skip non existing resourceDirectory /Users/jxblum/cpdev/Packt/Building Intelligent Applications with Spring AI/spring-ai-examples/example-one/src/test/resources
[INFO]
[INFO] --- compiler:3.14.0:testCompile (default-testCompile) @ example-one ---
[INFO] No sources to compile
[INFO]
[INFO] <<< spring-boot:3.5.0:run (default-cli) < test-compile @ example-one <<<
[INFO]
[INFO]
[INFO] --- spring-boot:3.5.0:run (default-cli) @ example-one ---
[INFO] Attaching agents: []

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.5.0)

2025-05-28T10:49:07.728-07:00  INFO 36303 --- [Deep Thought] [           main] c.p.s.a.e.one.DeepThoughtApplication     : Starting DeepThoughtApplication using Java 17.0.14 with PID 36303 (~~/Building Intelligent Applications with Spring AI/spring-ai-examples/example-one/target/classes started by jxblum in ~/Building Intelligent Applications with Spring AI/spring-ai-examples/example-one)
2025-05-28T10:49:07.730-07:00  INFO 36303 --- [Deep Thought] [           main] c.p.s.a.e.one.DeepThoughtApplication     : The following 1 profile is active: "user"
2025-05-28T10:49:08.383-07:00  INFO 36303 --- [Deep Thought] [           main] c.p.s.a.e.one.DeepThoughtApplication     : Started DeepThoughtApplication in 0.874 seconds (process running for 1.077)
User> In a single word, 'what is the answer to life, the universe, and everything?'

AI> 42

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.216 s
[INFO] Finished at: 2025-05-28T10:49:09-07:00
[INFO] ------------------------------------------------------------------------
----

This example currently supports 3 different AI models: [ OpenAI, Google Vertex AI Gemini, Ollama ].

Use the following Maven Profile IDs:

* openai (default)
* ollama
* gemini

To activate another AI provider model, such as Ollama (running locally), simply execute:

[source,shell]
----
$ mvnw --projects example-one -P ollama spring-boot:run
----

> NOTE: You must have installed Ollama locally (see https://ollama.com/download[download]) to run Ollama https://ollama.com/search[models], such as https://ollama.com/library/llama3.2[llama3.2]. You must run (automatically install) different AI models locally (e.g. `$ ollama run llama3.2`) before running Spring AI applications that use the model.
